repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.6.3
    hooks:
      - id: ruff
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: destroyed-symlinks
  - repo: https://github.com/tcort/markdown-link-check
    rev: v3.12.2
    hooks:
    - id: markdown-link-check
  - repo: https://github.com/Mateusz-Grzelinski/actionlint-py
    rev: v1.7.1.15
    hooks:
      - id: actionlint
        additional_dependencies: [pyflakes>=3.2, shellcheck-py>=0.10]
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.10.0.1
    hooks:
    - id: shellcheck
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.0.3
    hooks:
    - id: editorconfig-checker
      alias: ec
  # this should go last since it will fix line endings broken by other tools
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: no-commit-to-branch
      args: [--branch, main]
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: check-case-conflict
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-xml
    - id: check-json
    - id: check-toml
    - id: pretty-format-json
      args: [--autofix, --no-sort-keys, --indent=4]
      exclude: .*\.ipynb$
    - id: check-symlinks
    - id: debug-statements
    - id: fix-byte-order-marker
