on: pull_request

name: Git

jobs:
  message-check:
    name: Sanity Checks

    runs-on: ubuntu-24.04

    steps:
    - name: Block Autosquash Commits
      uses: xt0rted/block-autosquash-commits-action@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v6
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: '3.12'
        enable-cache: true
    - name: Install dependencies
      run: uv sync --frozen --extra ci
    - name: Run pre-commit
      run: uv run --frozen pre-commit run -a
