on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

name: pytest
jobs:
  py-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.py }})
    strategy:
      fail-fast: false
      matrix:
        config:
        - {os: windows-latest, py: '3.7'}
        - {os: macOS-latest, py: '3.8'}
        - {os: ubuntu-latest, py: '3.9'}
        - {os: ubuntu-latest, py: '3.10'}

    env:
      SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
      OS: ${{ matrix.config.os }}
      PYTHON: ${{ matrix.config.py }}
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ github.token }}
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.config.py }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[ci]
    - name: Install MPI (linux)
      if: contains(matrix.config.os, 'ubuntu')
      run: |
        sudo apt-get update
        sudo apt-get install -y mpi-default-dev
        pip install mpi4py
    - name: Download Microsoft MPI
      if: contains(matrix.config.os, 'windows')
      run: (new-object net.webclient).DownloadFile("https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisetup.exe",
        "msmpisetup.exe")
      shell: powershell
    - name: Install MPI (win)
      if: contains(matrix.config.os, 'windows')
      run: |
        msmpisetup.exe -unattend -minimal
        pip install mpi4py
      shell: cmd
    - name: Install MPI (osx)
      if: contains(matrix.config.os, 'macOS')
      run: |
        brew install openmpi
        pip install mpi4py
    - name: run pytest
      run: |
        pytest
    - name: "Upload coverage"
      uses: codecov/codecov-action@v1
      with:
        env_vars: OS,PYTHON
        fail_ci_if_error: true
    - name: build docs
      run: |
        python -m pip install .[docs]
        make -C docs html
